package com.learningpath.learningpath.dto;

import java.util.List;

public record AdaptLearningPathResponse(

        /**
         * True if the path was regenerated due to a detected learner state change.
         * False if the current path is still optimal and no regeneration occurred.
         */
        boolean adapted,

        /**
         * Human-readable explanation of why adaptation was (or was not) triggered.
         * Computed deterministically — not generated by AI.
         */
        String changeReason,

        /**
         * Skills the learner has already mastered (ADVANCED/EXPERT proficiency
         * or completed all associated courses). Computed deterministically.
         */
        List<String> completedSkills,

        /**
         * Skills remaining in the learner's skill gap that have not yet been mastered.
         * Computed deterministically from the skill gap engine and learner state.
         */
        List<String> remainingSkills,

        /**
         * The current (or newly adapted) personalized learning path.
         */
        PersonalizedLearningPathResponse path
) {
    public static AdaptLearningPathResponse unchanged(
            String reason,
            List<String> completedSkills,
            List<String> remainingSkills,
            PersonalizedLearningPathResponse path) {
        return new AdaptLearningPathResponse(false, reason, completedSkills, remainingSkills, path);
    }

    public static AdaptLearningPathResponse adapted(
            String reason,
            List<String> completedSkills,
            List<String> remainingSkills,
            PersonalizedLearningPathResponse path) {
        return new AdaptLearningPathResponse(true, reason, completedSkills, remainingSkills, path);
    }
}
